name: Update Releases

on:
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-releases:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run npm Install
        run: npm install

      - name: Run Releases Docs Generator Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node release-notes-generator.js

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: updated releases"
          branch: update-releases
          branch-suffix: timestamp
          base: develop
          title: "chore: updated releases"
          body: |
            This is an auto-generated pull request that updates releases.
          reviewers: tusharmath
          maintainer-can-modify: true
