name: Update Releases

on:
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  update-releases:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run npm Install
        run: npm install

      - name: Run Releases Docs Generator Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node release-notes-generator.js

      - name: Commit and push changes (on develop)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_author: Author <actions@github.com>
          commit_message: "chore: updated releases"
